# AUTOGENERATED Dockerfile using runpodctl project build

# Base image -> https://github.com/runpod/containers/blob/main/official-templates/base/Dockerfile
# DockerHub -> https://hub.docker.com/r/runpod/base/tags
FROM runpod/pytorch:2.8.0-py3.11-cuda12.8.1-cudnn-devel-ubuntu22.04

# The RunPod base image pre-installs many system dependencies to help you get started quickly.
# Check the base image's Dockerfile before adding more dependencies.
# IMPORTANT: The base image overrides the default Hugging Face cache location.

# System dependencies
# If you need system dependencies that are not included in the base image, add them here.
# You must override the base image in runpod.toml with an image that includes your dependencies
# for changes to propagate to your Project pod.

RUN python -m pip install --upgrade pip
# RUN pip install --no-cache-dir \
#     torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128

ADD . /asd/
RUN chmod +x /asd/src/setup.sh

EXPOSE 8188

ENTRYPOINT ["/asd/src/setup.sh"]
